import type { Metadata } from "next";
import "./globals.css";

import { Kanit, Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: "--font-poppins"
})

const kanit = Kanit({
  subsets: ['latin'],
  weight: ['900', '800', '700'],
  variable: "--font-kanit"
})

export const metadata: Metadata = {
  title: "Authentication using Next.js + Supabase",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`dark ${poppins.className} ${kanit.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
